#!/bin/sh
### BEGIN INIT INFO
# Provides:          cloudvpn
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: CloudVPN service
### END INIT INFO
# /etc/init.d/cloudvpn
#
# Written by Franck Royer <mail@franck-royer.fr>

set -e


DAEMON=/usr/local/sbin/cloudvpn
NAME=cloudvpn
CONFIGFILE=/etc/cloudvpn/$NAME.conf
LOGFILE=/var/log/cloudvpn.log
PIDFILE=/var/run/cloudvpn.pid

if test -e /etc/default/cloudvpn ; then
	. /etc/default/cloudvpn
fi

test -x $DAEMON || exit 0
test -x $LAUNCHSCRIPT || exit 0
. /lib/lsb/init-functions

startcloud()
{
	SUBMASK=${SUBMASK:-24}
	log_begin_msg "Starting Cloud VPN: $NAME"
	if [ -z "$IP" ] || [ -z "$TAP" ]
	then
		log_failure_msg " Please fill the /etc/default/cloudvpn file !"
		STATUS=1
	else
		start-stop-daemon --start -m --pidfile $PIDFILE --exec $DAEMON -- -@include $CONFIGFILE >> $LOGFILE &
		ps -p $(cat $PIDFILE) > /dev/null || log_end_msg 1
		log_daemon_msg "  ifconfig $TAP $IP/$SUBMASK"
		/sbin/ifconfig $TAP $IP/$SUBMASK && log_end_msg 0 || log_end_msg 1
	fi
	exit ${STATUS:-0}
}

case "$1" in
	start)
	startcloud
	;;
	stop)
	log_begin_msg "Stopping Cloud VPN: $NAME"
	start-stop-daemon --stop --pidfile $PIDFILE --oknodo && log_end_msg 0 || log_end_msg 1
	rm -f $PIDFILE
	;;
	restart)
	$0 stop
	$0 start
	;;
	*)
	log_success_msg "Usage: /etc/init.d/$NAME {start|stop|restart}"
	exit 1
	;;
esac

exit 0
