#!/bin/bash

[[ "$KEY" ]] || echo "please supply env KEY"
[[ "$REQ" ]] || echo "please supply env REQ"

[[ "$KEY" && "$REQ" ]] || exit 1

DAYS=${DAYS:-3650}
SIZE=${SIZE:-2048}

openssl req -new -newkey rsa:$SIZE -keyout $KEY -out $REQ -days $DAYS -nodes

