#!/bin/bash

[[ "$1" ]] || echo "Usage: $0 <keyname-without-extension>"

DAYS=${DAYS:-3650}

[[ "$1" ]] || exit 1

openssl ca -config ssl.cnf -out $1.crt -outdir ./ \
	-days $DAYS -batch -keyfile ca.key \
	-infiles $1.req

