#!/bin/sh
#

# PROVIDE: cloudvpn

# Add the following line to /etc/rc.conf to enable `cloudvpn':
#
# cloudvpn_enable="YES"
# cloudvpn_if="tapX"
# cloudvpn_ip="some_ip"
# cloudvpn_submask="255.255.255.0"
# cloudvpn_logfile="/var/log/cloudvpn.log"
#
# TODO : take the iface dev from the config file instead of /etc/rc.conf
# Written by Franck Royer <mail@franck-royer.fr>

. "/etc/rc.subr"

name="cloudvpn"
rcvar=`set_rcvar`

load_rc_config "$name"
: ${cloudvpn_enable:="NO"}
: ${cloudvpn_if:=""}
: ${cloudvpn_ip:=""}
: ${cloudvpn_submask:="255.255.255.0"}
: ${cloudvpn_logfile:="/var/log/$name.log"}

command="/usr/local/libexec/$name"
required_files="/usr/local/etc/cloudvpn/$name.conf"
#argument_cmd="-@include $required_files >> $cloudvpn_logfile &"
command_args="-@include $required_files >> $cloudvpn_logfile &"
#start_cmd="cloudvpn_start"
start_precmd="cloudvpn_init"
start_postcmd="cloudvpn_postinit"
stop_postcmd="cloudvpn_poststop"

cloudvpn_start()
{
	echo "Start $name."
	/usr/local/libexec/$name -@include $required_files >> $cloudvpn_logfile &
}


cloudvpn_init()
{
	if [ -z $cloudvpn_if ]
	then
		err 1 "Please add cloudvpn_if="tapX" in /etc/rc.conf"
	fi
	if [ -z $cloudvpn_ip ]
	then
		err 1 "Please add cloudvpn_ip="some_ip" in /etc/rc.conf"
	fi
	if [ -c "/dev/$cloudvpn_if" ]
	then
		echo "$cloudvpn_if already exists"
	else
		echo "Create $cloudvpn_if"
		/sbin/ifconfig $cloudvpn_if create
	fi
}
cloudvpn_postinit()
{
	echo "Configure $cloudvpn_if" 
	/sbin/ifconfig $cloudvpn_if $cloudvpn_ip netmask $cloudvpn_submask
}
cloudvpn_poststop()
{
	echo "Destroy $cloudvpn_if"
	/sbin/ifconfig $cloudvpn_if destroy
}

run_rc_command "$1"

